// Fallback data shown when CAP backend is unavailable.
// Matches the shape produced by tenderApi.js → toReactShape().
export const INITIAL_TENDERS = [
  {
    id: 'TND-001',
    tenderNo: 'MTL/MMRC/2026/T-01',
    version: 1,
    title: 'Construction of Metro Line 4A – Elevated Corridor',
    createdBy: 'Alice',
    lastReviewedBy: '-',
    lastChangedBy: 'Alice',
    details: {
      budget: '₹12,000 Crore',
      deadline: '2026-12-31',
      status: 'Draft',
      location: 'Mumbai, Maharashtra',
      contractor: 'Not Selected',
    },
    remarks: [],
  },
  {
    id: 'TND-002',
    tenderNo: 'SGPD/BER/2026/T-03',
    version: 3,
    title: 'Smart Grids Power Distribution Upgrade – Zone 4',
    createdBy: 'David',
    lastReviewedBy: 'Emily',
    lastChangedBy: 'Emily',
    details: {
      budget: '€38,000,000',
      deadline: '2026-10-15',
      status: 'Reviewed',
      location: 'Berlin, Germany',
      contractor: 'Siemens AG',
    },
    remarks: [],
  },
  {
    id: 'TND-003',
    tenderNo: 'WTF/AUS/2026/T-07',
    version: 2,
    title: 'Waste Treatment Facility Upgrade – Phase 2',
    createdBy: 'Sarah',
    lastReviewedBy: 'Robert',
    lastChangedBy: 'Robert',
    details: {
      budget: '$18,000,000',
      deadline: '2027-03-01',
      status: 'Approved',
      location: 'Austin, Texas',
      contractor: 'GreenWaste Inc',
    },
    remarks: [],
  },
];
