[project]
name = "python-ai-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1",
    "flask-cors>=5.0",
    "gunicorn>=21.0",
    "llama-index-core>=0.14.23",
    "llama-index-embeddings-huggingface>=0.7.0",
    "llama-index-retrievers-bm25>=0.7.1",
    "llama-index-storage-index-store-postgres>=0.6.0",
    "llama-index-vector-stores-postgres>=0.8.1",
    "pgvector>=0.4.2",
    "pillow>=11.0",
    "psycopg2-binary>=2.9.12",
    "pymupdf>=1.27",
    "pypdf>=5.0",
    "python-dotenv>=1.1",
    "reportlab>=4.0",
    "requests>=2.32",
    "sentence-transformers>=5.6.0",
]
